spring:
  profiles:
    active: dev
  mvc:
    pathmatch: matching-strategy=ant_path_matcher
  datasource:
    driverClassName : org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springboot
    username: root
    password: Florida12@3

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
upbit:
  wsuri : "wss://api.upbit.com/websocket/v1"


---
spring:
  config:
    activate:
      on-profile : prod